apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "rndflow-executor.fullname" . }}-high-priority
value: {{ .Values.priority.high }}
preemptionPolicy: Never
globalDefault: false
