{{- if .Values.jupyter.enabled -}}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" -}}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end}}
kind: Ingress
metadata:
  name: {{ include "rndflow-executor.fullname" . }}-jupyter-ingress
{{- with .Values.jupyter.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.jupyter.ingress.tls }}
  tls:
{{ toYaml .Values.jupyter.ingress.tls | indent 4 }}
{{- end }}
  rules:
    - http:
        paths:
          - path: {{ .Values.jupyter.ingress.path }}
            pathType: Prefix
            backend:
              {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
              service:
                name: {{ include "rndflow-executor.fullname" . }}-jupyter-proxy-svc
                port:
                  number: {{ .Values.jupyter.service.port }}
              {{- else }}
              serviceName: {{ include "rndflow-executor.fullname" . }}-jupyter-proxy-svc
              servicePort: {{ .Values.jupyter.service.port }}
              {{-  end }}
      {{- if .Values.jupyter.ingress.hostname }}
      host: {{ .Values.jupyter.ingress.hostname | quote }}
      {{- end }}
{{- end}}
