apiVersion: v1
kind: Service
metadata:
  name: {{ include "rndflow-server.fullname" . }}-api-svc
spec:
  selector:
    app: {{ include "rndflow-server.fullname" . }}-api
  ports:
  - protocol: TCP
    port: 8000
    targetPort: http

