apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rndflow-server.fullname" . }}-branding-config
data:
{{ if .Values.config.logo }}
  logo.svg: |
{{ .Values.config.logo | indent 4 }}
{{ end }}
{{ if .Values.config.leftFooter }}
  leftFooter: |
{{ .Values.config.leftFooter | indent 4 }}
{{ end }}
{{ if .Values.config.rightFooter }}
  rightFooter: |
{{ .Values.config.rightFooter | indent 4 }}
{{ end }}
