apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rndflow-server.fullname" . }}-docs
  labels:
    app: {{ include "rndflow-server.fullname" . }}-docs
spec:
  selector:
    matchLabels:
      app: {{ include "rndflow-server.fullname" . }}-docs
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "rndflow-server.fullname" . }}-docs
    spec:
      {{ if .Values.config.imagePullSecret }}
      imagePullSecrets:
        - name: "{{ .Values.config.imagePullSecret }}"
      {{ end }}
      containers:
        - name: nginx
          image: "{{ .Values.config.registry }}/{{ .Values.docs.image }}"
          resources:
{{ toYaml .Values.docs.resources | indent 12 }}

