# Default values for rndflow-executor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
config:
  registry:
  image: "rndflow/executor:latest"
  replicas: 1
  defaultJobImage: "rndflow/job.py:latest"
  apiHost:
  executorLabel:
  keySecret:
  nodeSelector:
  gpuVendor: "nvidia"
  #imagePullSecret: dockercred
  imagePullPolicy: "Always"
  #executor_max_pods:
  #executor_max_pods_pause: 60
  #executor_jobs_batch_size: 10
  #nodeName:
  #affinity:

  resources: {}
  #  requests:
  #     cpu: 10m
  #     memory: 32Mi
  #  limits:
  #     cpu: 100m
  #     memory: 200Mi

  storage: {}
  #  create_pod_pvc: false
  #  use_subpath: false
  #  access_modes: "ReadWriteOnce"
  #  pod_pvc_storage_class: "standard"
  #  pod_pvc_request_storage_size: "1Gi"

jupyter:
  enabled: false
  externalHost:
  idleLimit: 24
  ingress:
    hostname:
    path: /jupyter
    tls:
    # Secrets must be manually created in the namespace.
    #  - secretName: rndflow-tls
    #    hosts:
    #    - rndflow.local
    #
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 128m
  service:
    type: ClusterIP
    port: 8000
    clusterIP:
    nodePort:
    externalIPs:
  resources: {}
  #  requests:
  #     cpu: 10m
  #     memory: 32Mi
  #  limits:
  #     cpu: 100m
  #     memory: 200Mi

priority:
  low: 1000
  normal: 10000
  high: 100000
