apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rndflow-server.fullname" . }}-api
  labels:
    app: {{ include "rndflow-server.fullname" . }}-api
spec:
  selector:
    matchLabels:
      app: {{ include "rndflow-server.fullname" . }}-api
  replicas: {{ .Values.api.replicas }}
  template:
    metadata:
      labels:
        app: {{ include "rndflow-server.fullname" . }}-api
    spec:
      {{ if .Values.config.imagePullSecret }}
      imagePullSecrets:
        - name: "{{ .Values.config.imagePullSecret }}"
      {{ end }}
      {{ if .Values.config.priorityClassName }}
      priorityClassName: "{{ .Values.config.priorityClassName }}"
      {{ end }}
      containers:
        - name: rndflow-api
          image: "{{ .Values.config.registry }}/{{ .Values.api.image }}"
          imagePullPolicy: {{ .Values.config.imagePullPolicy }}
          command:
            - './boot.sh'
          env:
            - name: PYTHONUNBUFFERED
              value: "yes"
            {{ if .Values.config.databasePoolSize }}
            - name: DATABASE_POOL_SIZE
              value: "{{ .Values.config.databasePoolSize }}"
            {{ end }}
            {{ if .Values.config.databasePoolTimeout }}
            - name: DATABASE_POOL_TIMEOUT
              value: "{{ .Values.config.databasePoolTimeout }}"
            {{ end }}
            {{ if .Values.config.databaseMaxOverflow }}
            - name: DATABASE_MAX_OVERFLOW
              value: "{{ .Values.config.databaseMaxOverflow }}"
            {{ end }}
            {{ if .Values.config.databaseEcho }}
            - name: DATABASE_ECHO
              value: "{{ .Values.config.databaseEcho }}"
            {{ end }}
            {{ if .Values.api.anyioThreadLimiter}}
            - name: ANYIO_THREAD_LIMITER
              value: "{{ .Values.api.anyioThreadLimiter }}"
            {{ end }}

            - name: GUNICORN_WORKERS
              value: '{{ default "4" .Values.api.gunicorn.workers }}'
            - name: GUNICORN_THREADS
              value: '{{ default "1" .Values.api.gunicorn.threads }}'
            - name: GUNICORN_WORKER_CONNECTIONS
              value: '{{ default "1000" .Values.api.gunicorn.workerConnections }}'
            - name: GUNICORN_MAX_REQUESTS
              value: '{{ default "0" .Values.api.gunicorn.maxRequests }}'
            - name: GUNICORN_TIMEOUT
              value: '{{ default "30" .Values.api.gunicorn.timeout }}'
            - name: GUNICORN_GRACEFUL_TIMEOUT
              value: '{{ default "30" .Values.api.gunicorn.gracefulTimeout }}'
            - name: GUNICORN_KEEPALIVE
              value: '{{ default "2" .Values.api.gunicorn.keepalive }}'

            {{ if .Values.config.bot }}
            {{ if .Values.config.bot.telegram }}
            {{ if .Values.config.bot.telegram.name }}
            - name: TELEGRAM_BOT_NAME
              value: "{{ .Values.config.bot.telegram.name }}"
            {{ end }}
            {{ if .Values.config.bot.telegram.token }}
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "rndflow-server.fullname" . }}-secrets
                  key: telegramBotToken
            {{ end }}
            {{ if .Values.config.bot.telegram.timeout }}
            - name: TELEGRAM_BOT_TIMEOUT
              value: "{{ .Values.config.bot.telegram.timeout }}"
            {{ end }}
            {{ if .Values.config.bot.telegram.subscriptionKeyValidity }}
            - name: TELEGRAM_BOT_SUBSCRIPTION_KEY_VALIDITY
              value: "{{ .Values.config.bot.telegram.subscriptionKeyValidity }}"
            {{ end }}
            {{ end }}
            {{ end }}

            {{ if .Values.config.s3 }}
            {{ if .Values.config.s3.cleanupSafePeriod }}
            - name: S3SERVER_CLEANUP_SAFE_PERIOD
              value: "{{ .Values.config.s3.cleanupSafePeriod }}"
            {{ end }}
            {{ if .Values.config.s3.pool }}
            {{ if .Values.config.s3.pool.timeout_connect }}
            - name: S3SERVER_POOL_TIMEOUT_CONNECT
              value: "{{ .Values.config.s3.pool.timeout_connect }}"
            {{ end }}
            {{ if .Values.config.s3.pool.timeout_read }}
            - name: S3SERVER_POOL_TIMEOUT_READ
              value: "{{ .Values.config.s3.pool.timeout_read }}"
            {{ end }}
            {{ if .Values.config.s3.pool.maxsize }}
            - name: S3SERVER_POOL_MAXSIZE
              value: "{{ .Values.config.s3.pool.maxsize }}"
            {{ end }}
            {{ if .Values.config.s3.pool.certReqs }}
            - name: S3SERVER_POOL_CERT_REQS
              value: "{{ .Values.config.s3.pool.certReqs }}"
            {{ end }}

            {{ if .Values.config.s3.pool.retries }}
            {{ if .Values.config.s3.pool.retries.total }}
            - name: S3SERVER_POOL_RETRIES_TOTAL
              value: "{{ .Values.config.s3.pool.retries.total }}"
            {{ end }}
            {{ if .Values.config.s3.pool.retries.backoffFactor }}
            - name: S3SERVER_POOL_RETRIES_BACKOFF_FACTOR
              value: "{{ .Values.config.s3.pool.retries.backoffFactor }}"
            {{ end }}
            {{ end }}
            {{ end }}
            {{ end }}

            {{ if .Values.config.options }}
            {{ if  hasKey .Values.config.options "useBulkSave" }}
            - name: OPTIONS_USE_BULK_SAVE
              value: "{{ .Values.config.options.useBulkSave }}"
            {{ end }}
            {{ if  hasKey .Values.config.options "useCelerySave" }}
            - name: OPTIONS_USE_CELERY_SAVE
              value: "{{ .Values.config.options.useCelerySave }}"
            {{ end }}
            {{ if  hasKey .Values.config.options "checkS3FilesWithDatabase" }}
            - name: OPTIONS_CHECK_S3FILES_WITH_DATABASE
              value: "{{ .Values.config.options.checkS3FilesWithDatabase }}"
            {{ end }}
            {{ if  hasKey .Values.config.options "useS3RegionsCache" }}
            - name: OPTIONS_USE_S3REGIONS_CACHE
              value: "{{ .Values.config.options.useS3RegionsCache }}"
            {{ end }}
            {{ end }}

            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "rndflow-server.fullname" . }}-secrets
                  key: databaseUri
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "rndflow-server.fullname" . }}-secrets
                  key: rabbitmqUri
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ include "rndflow-server.fullname" . }}-secrets
                  key: adminEmail
            - name: AUTHJWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "rndflow-server.fullname" . }}-secrets
                  key: apiSecret
            - name: MAIL_SERVER
              value: {{  required ".Values.email.server is required" .Values.email.server }}
            - name: MAIL_PORT
              value: {{  required ".Values.email.port is required" .Values.email.port | quote }}
            - name: MAIL_TLS
              value: {{  required ".Values.email.tls is required" .Values.email.tls | quote }}
            - name: MAIL_FROM
              value: {{  required ".Values.email.sender is required" .Values.email.sender }}
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "rndflow-server.fullname" . }}-secrets
                  key: email_username
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "rndflow-server.fullname" . }}-secrets
                  key: email_password
          lifecycle:
            preStop:
              exec:
                command: ['/bin/bash', '-c', 'kill -SIGTERM $(cat /rndflow/pid)']
          resources:
{{ toYaml .Values.api.resources | indent 12 }}
          ports:
            - name: http
              containerPort: 8000
      {{- if .Values.hostAliases }}
      hostAliases:
        {{- toYaml .Values.hostAliases | nindent 8 }}
      {{- end }}

      {{- if .Values.api.nodeName }}
      nodeName: "{{ .Values.api.nodeName }}"
      {{- end }}
      {{- if .Values.api.affinity }}
      affinity:
        {{- toYaml .Values.api.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.api.nodeSelector | nindent 8 }}
      {{- end }}
