apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "rndflow-server.fullname" . }}-builder-role
rules:
  - apiGroups: ["batch"]
    resources:
      - jobs
    verbs:
      - list
      - get
      - create
      - delete
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - list
      - watch
  - apiGroups: [""]
    resources:
      - pods/log
    verbs:
      - get
  - apiGroups: [""]
    resources:
      - events
    verbs:
      - list
      - watch
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - create
      - delete
