apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rndflow-server.fullname" . }}-docs
  labels:
    app: {{ include "rndflow-server.fullname" . }}-docs
spec:
  selector:
    matchLabels:
      app: {{ include "rndflow-server.fullname" . }}-docs
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "rndflow-server.fullname" . }}-docs
    spec:
      {{ if .Values.config.imagePullSecret }}
      imagePullSecrets:
        - name: "{{ .Values.config.imagePullSecret }}"
      {{ end }}
      containers:
        - name: nginx
          image: "{{ .Values.config.registry }}/{{ .Values.docs.image }}"
          imagePullPolicy: {{.Values.config.imagePullPolicy }}
          resources:
{{ toYaml .Values.docs.resources | indent 12 }}

      {{- if .Values.docs.nodeName }}
      nodeName: "{{ .Values.docs.nodeName }}"
      {{- end }}
      {{- if .Values.docs.affinity }}
      affinity:
        {{- toYaml .Values.docs.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.docs.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.docs.nodeSelector | nindent 8 }}
      {{- end }}
