apiVersion: v1
kind: Service
metadata:
  name: {{ include "rndflow-server.fullname" . }}-docs-svc
spec:
  selector:
    app: {{ include "rndflow-server.fullname" . }}-docs
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
