apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rndflow-server.fullname" . }}-secrets
type: Opaque
stringData:
  databaseUri: {{ required ".Values.config.databaseUri is required" .Values.config.databaseUri }}
  rabbitmqUri: {{ required ".Values.config.rabbitmqUri is required" .Values.config.rabbitmqUri }}
  adminEmail: {{ required ".Values.config.adminEmail is required" .Values.config.adminEmail }}
  apiSecret: {{  required ".Values.api.secret is required" .Values.api.secret }}
  email_username: {{ required ".Values.email.username is required" .Values.email.username }}
  email_password: {{ required ".Values.email.password is required" .Values.email.password }}
