# Default values for rndflow-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

config:
  registry:
  databaseUri:
  rabbitmqUri:
  adminEmail:

  logo:
  leftFooter:
  rightFooter:

  #imagePullSecret: dockercred
  imagePullPolicy: "Always"

  #priorityClassName: "system-cluster-critical"

  #databasePoolSize: 100
  #databaseMaxOverflow: 500
  #databaseEcho: true

  #S3 server cleanup files safe period in days. For minutes use 0.00069 multiplier, for hours - 0.042.
  #s3cleanup_safe_period: 1

#  minioPool:
    # https://urllib3.readthedocs.io/en/stable/reference/urllib3.connectionpool.html
    #timeout:
    #maxsize: 10
    # https://docs.python.org/3/library/ssl.html#ssl.wrap_socket
    #certReqs: 'CERT_NONE'
    # https://urllib3.readthedocs.io/en/latest/reference/urllib3.util.html#urllib3.util.Retry
    #retries:
      #total: 5
      #backoffFactor: 0.2
api:
  replicas: 1
  workers: 4 
  image: "rndflow/api:latest"
  secret:
  resources: {}
  #  requests:
  #     cpu: 300m
  #     memory: 500Mi
  #  limits:
  #     cpu: 4
  #     memory: 10Gi
  #nodeName:
  #affinity:
  #nodeSelector:

celery:
  replicas: 1
  resources: {}
  #  requests:
  #     cpu: 100m
  #     memory: 450Mi
  #  limits:
  #     cpu: 1
  #     memory: 1Gi
  #nodeName:
  #affinity:
  #nodeSelector:


pgRmqProxy:
  image: "rndflow/pg-rmq-proxy:latest"
  resources: {}
  #  requests:
  #     cpu: 100m
  #     memory: 100Mi
  #  limits:
  #     cpu: 1
  #     memory: 1Gi
  #nodeName:
  #affinity:
  #nodeSelector:


frontend:
  replicas: 1
  image: "rndflow/client:latest"
  # Enable root image user  
  imageRootMode: false 
  ingress:
    enabled: false
    hostname:
    annotations: {}
    tls:
    # Secrets must be manually created in the namespace.
    # - secretName: rndflow-tls
    #   hosts:
    #     - rndflow.local
  service:
    type: ClusterIP
    port: 8080
    clusterIP:
    nodePort:
    externalIPs:
  resources: {}
  #  requests:
  #     cpu: 200m
  #     memory: 200Mi
  #  limits:
  #     cpu: 1
  #     memory: 10Gi
  init:
    resources: {}
    #  requests:
    #     cpu: 200m
    #     memory: 200Mi
    #  limits:
    #     cpu: 1
    #     memory: 10Gi
  #nodeName:
  #affinity:
  #nodeSelector:

s3cleanup:
  enabled: true
  schedule: "@midnight"
  resources: {}
  #  requests:
  #     cpu: 300m
  #     memory: 500Mi
  #  limits:
  #     cpu: 2
  #     memory: 2Gi

builder:
  jobPrefix: "rndflow-builder"
  image: "rndflow/docker-init:latest"

docs:
  image: "rndflow/documentation:latest"
  resources: {}
  #  requests:
  #     cpu: 200m
  #     memory: 200Mi
  #  limits:
  #     cpu: 1
  #     memory: 1Gi
  #nodeName:
  #affinity:
  #nodeSelector:

email:
  server: "smtp.gmail.com"
  port: 587
  tls: true
  ssl: false
  use_credentials: true
  username:
  password:
  sender:

hostAliases: []
#hostAliases:
##- ip: "10.10.0.1"
##  hostnames:
##  - "host1"
##- ip: "10.100.0.2"
##  hostnames:
##  - "host2"

