{{- if .Values.jupyter.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rndflow-executor.fullname" . }}-event-watcher
  labels:
    app: {{ include "rndflow-executor.fullname" . }}-event-watcher
spec:
  selector:
    matchLabels:
      app: {{ include "rndflow-executor.fullname" . }}-event-watcher
  replicas: {{ .Values.config.replicas }}
  template:
    metadata:
      labels:
        app: {{ include "rndflow-executor.fullname" . }}-event-watcher
    spec:
      serviceAccountName: {{ include "rndflow-executor.fullname" . }}-account
      {{ if .Values.config.imagePullSecret }}
      imagePullSecrets:
        - name: "{{ .Values.config.imagePullSecret }}"
      {{ end }}
      containers:
        - name: event-watcher
          image: "{{ .Values.config.registry }}/{{ .Values.config.image }}"
          imagePullPolicy: {{.Values.config.imagePullPolicy }}  
          command:
            - "./boot.sh"
            - "event-watcher"
          env:
            - name: EXECUTOR_API_SERVER
              value: {{ required ".Values.config.apiHost is required" .Values.config.apiHost }}
            - name: EXECUTOR_LABEL
              value: {{ .Values.config.executorLabel }}
            - name: EXECUTOR_NAMESPACE
              value: {{ .Release.Namespace | default "default" }}
            - name: EXECUTOR_NODE_SELECTOR
              value: {{ .Values.config.nodeSelector }}
            - name: EXECUTOR_JOB_PREFIX
              value: {{ .Release.Name }}-job
            - name: PYTHONUNBUFFERED
              value: "yes"
            {{- if .Values.jupyter.enabled }}
            - name: EXECUTOR_JUPYTER_SVC
              value: {{ include "rndflow-executor.fullname" . }}-jupyter-proxy-svc
            - name: EXECUTOR_JUPYTER_IDLE_LIMIT
              value: "{{ .Values.jupyter.idleLimit }}"
            {{- end }}
          resources:
{{ toYaml .Values.config.resources | indent 12 }}
          volumeMounts:
            - name: key
              mountPath: "/rndflow/private"
              readOnly: true
      volumes:
        - name: key
          secret:
            secretName: {{ required ".Values.config.keySecret is required" .Values.config.keySecret }}

      {{- if .Values.config.nodeName }}
      nodeName: "{{ .Values.config.nodeName }}"
      {{- end }}
      {{- if .Values.config.affinity }}
      affinity:
        {{- toYaml .Values.config.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.config.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.config.nodeSelector | nindent 8 }}
      {{- end }}

{{- end}}
