apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rndflow-executor.fullname" . }}-executor
  labels:
    app: {{ include "rndflow-executor.fullname" . }}-executor
spec:
  selector:
    matchLabels:
      app: {{ include "rndflow-executor.fullname" . }}-executor
  replicas: {{ .Values.config.replicas }}
  template:
    metadata:
      labels:
        app: {{ include "rndflow-executor.fullname" . }}-executor
    spec:
      serviceAccountName: {{ include "rndflow-executor.fullname" . }}-account
      {{ if .Values.config.imagePullSecret }}
      imagePullSecrets:
        - name: "{{ .Values.config.imagePullSecret }}"
      {{ end }}
      containers:
        - name: executor
          image: "{{ .Values.config.registry }}/{{ .Values.config.image }}"
          imagePullPolicy: {{.Values.config.imagePullPolicy }}
          command:
            - "./boot.sh"
            - "executor"
          env:
            - name: EXECUTOR_API_SERVER
              value: {{ required ".Values.config.apiHost is required" .Values.config.apiHost }}
            - name: EXECUTOR_LABEL
              value: {{ .Values.config.executorLabel }}
            - name: EXECUTOR_NAMESPACE
              value: {{ .Release.Namespace | default "default" }}
            - name: EXECUTOR_NODE_SELECTOR
              value: {{ .Values.config.nodeSelector }}
            - name: EXECUTOR_JOB_PREFIX
              value: {{ .Release.Name }}-job
            - name: EXECUTOR_GPU_VENDOR
              value: {{ .Values.config.gpuVendor }}
            - name: EXECUTOR_DEFAULT_JOB_IMAGE
              value: {{ .Values.config.defaultJobImage }}
            - name: EXECUTOR_LOW_PRIORITY
              value: {{ include "rndflow-executor.fullname" . }}-low-priority
            - name: EXECUTOR_NORMAL_PRIORITY
              value: {{ include "rndflow-executor.fullname" . }}-normal-priority
            - name: EXECUTOR_HIGH_PRIORITY
              value: {{ include "rndflow-executor.fullname" . }}-high-priority
            - name: PYTHONUNBUFFERED
              value: "yes"

            {{- if .Values.config.storage.create_pod_pvc }}
            - name: EXECUTOR_CREATE_POD_PVC
              value: "{{ .Values.config.storage.create_pod_pvc }}"
            {{- end }}
            {{- if .Values.config.storage.use_subpath }}
            - name: EXECUTOR_USE_SUBPATH
              value: "{{ .Values.config.storage.use_subpath }}"
            {{- end }}
            {{- if .Values.config.storage.access_modes }}
            - name: EXECUTOR_ACCESS_MODES
              value: {{ .Values.config.storage.access_modes }}
            {{- end }}
            {{- if .Values.config.storage.pod_pvc_storage_class }}
            - name: EXECUTOR_POD_PVC_STORAGE_CLASS
              value: {{ .Values.config.storage.pod_pvc_storage_class }}
            {{- end }}
            {{- if .Values.config.storage.pod_pvc_request_storage_size }}
            - name: EXECUTOR_POD_PVC_REQUEST_STORAGE_SIZE
              value: {{ .Values.config.storage.pod_pvc_request_storage_size }}
            {{- end }}
            {{- if .Values.config.storage.pod_pvc_created_pause }}
            - name: EXECUTOR_POD_PVC_CREATED_PAUSE
              value: {{ .Values.config.storage.pod_pvc_created_pause | quote }}
            {{- end }}

            {{- if .Values.config.executor_max_pods }}
            - name: EXECUTOR_MAX_PODS
              value: {{ .Values.config.executor_max_pods | quote }}
            {{- end }}
            {{- if .Values.config.executor_max_pods_pause }}
            - name: EXECUTOR_MAX_PODS_PAUSE
              value: {{ .Values.config.executor_max_pods_pause | quote }}
            {{- end }}
            {{- if .Values.config.executor_jobs_batch_size }}
            - name: EXECUTOR_JOBS_BATCH_SIZE
              value: {{ .Values.config.executor_jobs_batch_size | quote }}
            {{- end }}
            {{- if .Values.config.jobs_start_pause }}
            - name: EXECUTOR_JOBS_START_PAUSE
              value: {{ .Values.config.jobs_start_pause | quote }}
            {{- end }}
            {{- if .Values.config.jobs_image_pull_policy }}
            - name: EXECUTOR_JOBS_IMAGE_PULL_POLICY
              value: {{ .Values.config.jobs_image_pull_policy | quote }}
            {{- end }}
            {{- if .Values.config.jobs_image_pull_secret }}
            - name: EXECUTOR_JOBS_IMAGE_PULL_SECRET
              value: {{ .Values.config.jobs_image_pull_secret | quote }}
            {{- end }}
            {{- if .Values.config.restart_period }}
            - name: EXECUTOR_RESTART_PERIOD
              value: {{ .Values.config.restart_period | quote }}
            {{- end }}
            {{- if .Values.config.logging_level }}
            - name: EXECUTOR_LOGGING_LEVEL
              value: {{ .Values.config.logging_level }}
            {{- end }}

            {{- if .Values.jupyter.enabled }}
            - name: EXECUTOR_JUPYTER_ENABLED
              value: "{{ .Values.jupyter.enabled }}"
            - name: EXECUTOR_JUPYTER_PATH
              value: {{ required ".Values.jupyter.ingress.path is required" .Values.jupyter.ingress.path }}
            {{- end }}
          resources:
{{ toYaml .Values.config.resources | indent 12 }}
          volumeMounts:
            - name: key
              mountPath: "/rndflow/private"
              readOnly: true
      volumes:
        - name: key
          secret:
            secretName: {{ required ".Values.config.keySecret is required" .Values.config.keySecret }}

      {{- if .Values.config.nodeName }}
      nodeName: "{{ .Values.config.nodeName }}"
      {{- end }}
      {{- if .Values.config.affinity }}
      affinity:
        {{- toYaml .Values.config.affinity | nindent 8 }}
      {{- end }}
