{{- if .Values.jupyter.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rndflow-executor.fullname" . }}-jupyter-proxy
  labels:
    app: {{ include "rndflow-executor.fullname" . }}-jupyter-proxy
spec:
  selector:
    matchLabels:
      app: {{ include "rndflow-executor.fullname" . }}-jupyter-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "rndflow-executor.fullname" . }}-jupyter-proxy
    spec:
      {{ if .Values.config.imagePullSecret }}
      imagePullSecrets:
        - name: "{{ .Values.config.imagePullSecret }}"
      {{ end }}
      containers:
        - name: jupyter-proxy
          image: "jupyterhub/configurable-http-proxy"
          imagePullPolicy: {{.Values.config.imagePullPolicy }}
          ports:
            - name: proxy
              containerPort: 8000
            - name: api
              containerPort: 8001
          resources:
{{ toYaml .Values.jupyter.resources | indent 12 }}

      {{- if .Values.config.nodeName }}
      nodeName: "{{ .Values.config.nodeName }}"
      {{- end }}
      {{- if .Values.config.affinity }}
      affinity:
        {{- toYaml .Values.config.affinity | nindent 8 }}
      {{- end }}

{{- end}}
