apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "rndflow-executor.fullname" . }}-normal-priority
value: {{ .Values.priority.normal }}
preemptionPolicy: Never
globalDefault: false
