apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rndflow-executor.fullname" . }}-pod-watcher
  labels:
    app: {{ include "rndflow-executor.fullname" . }}-pod-watcher
spec:
  selector:
    matchLabels:
      app: {{ include "rndflow-executor.fullname" . }}-pod-watcher
  replicas: {{ .Values.config.replicas }}
  template:
    metadata:
      labels:
        app: {{ include "rndflow-executor.fullname" . }}-pod-watcher
    spec:
      serviceAccountName: {{ include "rndflow-executor.fullname" . }}-account
      {{ if .Values.config.imagePullSecret }}
      imagePullSecrets:
        - name: "{{ .Values.config.imagePullSecret }}"
      {{ end }}
      containers:
        - name: pod-watcher
          image: "{{ .Values.config.registry }}/{{ .Values.config.image }}"
          imagePullPolicy: {{.Values.config.imagePullPolicy }}
          command:
            - "./boot.sh"
            - "pod-watcher"
          env:
            - name: EXECUTOR_API_SERVER
              value: {{ required ".Values.config.apiHost is required" .Values.config.apiHost }}
            - name: EXECUTOR_LABEL
              value: {{ .Values.config.executorLabel }}
            - name: EXECUTOR_NAMESPACE
              value: {{ .Release.Namespace | default "default" }}
            - name: EXECUTOR_NODE_SELECTOR
              value: {{ .Values.config.nodeSelector }}
            - name: EXECUTOR_JOB_PREFIX
              value: {{ .Release.Name }}-job
            - name: PYTHONUNBUFFERED
              value: "yes"

            {{- if .Values.config.storage.create_pod_pvc }}
            - name: EXECUTOR_CREATE_POD_PVC
              value: "{{ .Values.config.storage.create_pod_pvc }}"
            {{- end }}
            {{- if .Values.config.storage.use_subpath }}
            - name: EXECUTOR_USE_SUBPATH
              value: "{{ .Values.config.storage.use_subpath }}"
            {{- end }}
            {{- if .Values.config.storage.access_modes }}
            - name: EXECUTOR_ACCESS_MODES
              value: {{ .Values.config.storage.access_modes }}
            {{- end }}
            {{- if .Values.config.storage.pod_pvc_storage_class }}
            - name: EXECUTOR_POD_PVC_STORAGE_CLASS
              value: {{ .Values.config.storage.pod_pvc_storage_class }}
            {{- end }}
            {{- if .Values.config.storage.pod_pvc_request_storage_size }}
            - name: EXECUTOR_POD_PVC_REQUEST_STORAGE_SIZE
              value: {{ .Values.config.storage.pod_pvc_request_storage_size }}
            {{- end }}

            {{- if .Values.jupyter.enabled }}
            - name: EXECUTOR_JUPYTER_SVC
              value: {{ include "rndflow-executor.fullname" . }}-jupyter-proxy-svc
            - name: EXECUTOR_JUPYTER_HOST
              value: {{ required ".Values.jupyter.externalHost is required" .Values.jupyter.externalHost }}
            - name: EXECUTOR_JUPYTER_PATH
              value: {{ required ".Values.jupyter.ingress.path is required" .Values.jupyter.ingress.path }}
            {{- end }}
          resources:
{{ toYaml .Values.config.resources | indent 12 }}
          volumeMounts:
            - name: key
              mountPath: "/rndflow/private"
              readOnly: true
      volumes:
        - name: key
          secret:
            secretName: {{ required ".Values.config.keySecret is required" .Values.config.keySecret }}

      {{- if .Values.config.nodeName }}
      nodeName: "{{ .Values.config.nodeName }}"
      {{- end }}
      {{- if .Values.config.affinity }}
      affinity:
        {{- toYaml .Values.config.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.config.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.config.nodeSelector | nindent 8 }}
      {{- end }}
