apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "rndflow-executor.fullname" . }}-role
rules:
  - apiGroups: ["batch"]
    resources:
      - jobs
    verbs:
      - list
      - get
      - create
      - delete
  - apiGroups: ["batch"]
    resources:
      - cronjobs
    verbs:
      - list
      - get
      - create
      - delete
      - patch
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - create
      - delete
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - list
      - watch
      - patch
  - apiGroups: [""]
    resources:
      - pods/log
    verbs:
      - get
  - apiGroups: [""]
    resources:
      - events
    verbs:
      - list
      - watch
  - apiGroups: ["metrics.k8s.io"]
    resources:
      - nodes
    verbs:
      - list
  - apiGroups: [""]
    resources:
      - persistentvolumeclaims
    verbs:
      - create
      - delete
      - list
