apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "rndflow-executor.fullname" . }}-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "rndflow-executor.fullname" . }}-account
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "rndflow-executor.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io

